from pydantic import BaseModel
from typing import List


class OrchestratorAgent(BaseModel):
    """Represents a single agent task in the orchestrator plan"""
    task: str
    prompt: str


class OrchestratorPlan(BaseModel):
    """Represents the plan generated by the orchestrator"""
    response: str
    agents: List[OrchestratorAgent]


class ChatRequest(BaseModel):
    """Request body for chat endpoint"""
    query: str


class SearchResult(BaseModel):
    """Represents a single search result"""
    position: int | None = None
    title: str
    link: str
    snippet: str


class ToolResult(BaseModel):
    """Represents a tool execution result"""
    type: str
    content: str | dict
